{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lyivx",
    "module": "lyivxs-tweaks-1.21.4-neoforge",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-neoforge-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-neoforge-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-neoforge-1.0.0.jar",
          "size": 779786,
          "sha512": "cc79434bc03208860e81f898f6cf41379bcc5c869c723a4889b15b933ae49536a5fd15f562257aaf47376e3d9f4a5f3133d8eafef08e9e76ece7c4be1f48c655",
          "sha256": "a7e55a00b09e9ebec39ab7e61d509b6ab83dd22c283d71d1690c7eac258105ab",
          "sha1": "ea8d7ad91cab2aa9882903d07a9cadb3731c7925",
          "md5": "3f6410bf8db35718089991143e20abc4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-neoforge-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-neoforge",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-common-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "curse.maven",
          "module": "lyivxs-core-1200581",
          "version": {
            "requires": "7018765"
          }
        }
      ],
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-neoforge-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-neoforge-1.0.0.jar",
          "size": 779786,
          "sha512": "cc79434bc03208860e81f898f6cf41379bcc5c869c723a4889b15b933ae49536a5fd15f562257aaf47376e3d9f4a5f3133d8eafef08e9e76ece7c4be1f48c655",
          "sha256": "a7e55a00b09e9ebec39ab7e61d509b6ab83dd22c283d71d1690c7eac258105ab",
          "sha1": "ea8d7ad91cab2aa9882903d07a9cadb3731c7925",
          "md5": "3f6410bf8db35718089991143e20abc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-neoforge-1.0.0-sources.jar",
          "url": "lyivxs-tweaks-1.21.4-neoforge-1.0.0-sources.jar",
          "size": 4509,
          "sha512": "77dd0d2695e7a609468bcb79c941aa98663cd816afe780f2de129cdcecb748945849c81a25739ac48163e3946419a2509bec7e63ca8a90a684106d4336db31dd",
          "sha256": "8dd36eaeda53046379920041a59d2e9c9055ebef71222603317fe9f05de3c3f8",
          "sha1": "53d1d58795258833f1a56b5f24495cf868e169e4",
          "md5": "000d0dd4f664b76ac572696f0107c94d"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-neoforge-1.0.0-dev-shadow.jar",
          "url": "lyivxs-tweaks-1.21.4-neoforge-1.0.0-dev-shadow.jar",
          "size": 333903,
          "sha512": "69f55deef56c5e3abb1114246a7ecb16cafcae9bf338e5433ab74045f0d68f1ce558f4da8e4be74a4707a0855140946e2a16da393d98d8facf6875b7cfc75986",
          "sha256": "e30286081ca1c7af5e58399a028ce1cdbad1076e374c59d3651c96163b71c81b",
          "sha1": "d4fa13debb5fb8d9a0f1627638d30bc5c0265b7c",
          "md5": "72962479b949131ae5331aebda045fe9"
        }
      ]
    }
  ]
}
