architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    modImplementation "dev.architectury:architectury:$rootProject.architectury_api_version"
    modImplementation "com.teamresourceful.resourcefullib:resourcefullib-common-1.21.4:3.4.5"

    modImplementation "curse.maven:lyivxs-core-1200581:7018764"

    modImplementation("curse.maven:furnection-914878:6928764")

}
