{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lyivx",
    "module": "lyivxs-tweaks-1.21.4-common",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-common-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-common-1.0.0.jar",
          "size": 331663,
          "sha512": "60a14bebcbe29bb4e7789c20210043d673590430d59ce29068a2d063c5a5f5d9e6e2b838107ec4da4b34f7413c94621a8057833f3ea8fdb7975c70d43eb5cd74",
          "sha256": "cdfe2a3003eaf33f2396906b7cb3ecd1cb2fd251aea3db6b3420e30099fcf2c1",
          "sha1": "e221294f2903268dbc6d5dee8d191c64f657780f",
          "md5": "28939b7cae128902a472c2d30dd2e80a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-common-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "curse.maven",
          "module": "lyivxs-core-1200581",
          "version": {
            "requires": "7018764"
          }
        },
        {
          "group": "curse.maven",
          "module": "furnection-914878",
          "version": {
            "requires": "6928764"
          }
        }
      ],
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-common-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-common-1.0.0.jar",
          "size": 331663,
          "sha512": "60a14bebcbe29bb4e7789c20210043d673590430d59ce29068a2d063c5a5f5d9e6e2b838107ec4da4b34f7413c94621a8057833f3ea8fdb7975c70d43eb5cd74",
          "sha256": "cdfe2a3003eaf33f2396906b7cb3ecd1cb2fd251aea3db6b3420e30099fcf2c1",
          "sha1": "e221294f2903268dbc6d5dee8d191c64f657780f",
          "md5": "28939b7cae128902a472c2d30dd2e80a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-common-1.0.0-sources.jar",
          "url": "lyivxs-tweaks-1.21.4-common-1.0.0-sources.jar",
          "size": 160195,
          "sha512": "5400ac01ab2b2a8b6e7b264288e9c9807f8d3b05a702b2767b63c0b603cd96fcdce356a020c3fab1ad75f9143be50edee69fdb6e60be3badabf466e346d70600",
          "sha256": "e06ec4fc47530749fd9c0e237f8e05a2dd25f3f425f0badbb7643a97d649eca1",
          "sha1": "1d71660b85bb49bf4a28e63d87e664aab51cdb72",
          "md5": "8c6db3db5d3bb0e9b268b61eb3e276dc"
        }
      ]
    }
  ]
}
