{
  "formatVersion": "1.1",
  "component": {
    "group": "net.lyivx",
    "module": "lyivxs-tweaks-1.21.4-fabric",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-fabric-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-fabric-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-fabric-1.0.0.jar",
          "size": 775258,
          "sha512": "73a5c71e6b742ef88b53bd4ade6ace7567ef838ced8ecc869082b77a5a0ac2832864102f7f454da479d97f02f57d0ea75d61486e2425208b05cc5625c8960b92",
          "sha256": "e5de4cf08452a9395b7416a992f237788309d4fb2f0e0cb3f9de886e6e2176b6",
          "sha1": "c43cbe6aef0b0ae07a348a4855f4ddd8204b7741",
          "md5": "d6b25f71f8509f43e7c74f7ed5be197c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.teamresourceful.resourcefullib",
          "module": "resourcefullib-fabric-1.21.4",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.119.4+1.21.4"
          }
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "15.0.3"
          }
        },
        {
          "group": "curse.maven",
          "module": "lyivxs-core-1200581",
          "version": {
            "requires": "7018763"
          }
        },
        {
          "group": "curse.maven",
          "module": "furnection-914878",
          "version": {
            "requires": "6928764"
          }
        }
      ],
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-fabric-1.0.0.jar",
          "url": "lyivxs-tweaks-1.21.4-fabric-1.0.0.jar",
          "size": 775258,
          "sha512": "73a5c71e6b742ef88b53bd4ade6ace7567ef838ced8ecc869082b77a5a0ac2832864102f7f454da479d97f02f57d0ea75d61486e2425208b05cc5625c8960b92",
          "sha256": "e5de4cf08452a9395b7416a992f237788309d4fb2f0e0cb3f9de886e6e2176b6",
          "sha1": "c43cbe6aef0b0ae07a348a4855f4ddd8204b7741",
          "md5": "d6b25f71f8509f43e7c74f7ed5be197c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-fabric-1.0.0-sources.jar",
          "url": "lyivxs-tweaks-1.21.4-fabric-1.0.0-sources.jar",
          "size": 5061,
          "sha512": "6bd93357b057292dd265cbb111940d51c0a61502af1de7b841345fb6193c92adba35b7eb0a6fbf51d02dd5f4ddfbe35cf46f93f1538c44105151f28f9309834e",
          "sha256": "1081ba9c8f08e6161005370aa814a7e13d3c871770b444f7b559dac672ebc667",
          "sha1": "2dcd37e0f0f4c256a337f84b74758096f69ab014",
          "md5": "7c5deb5622ace5db6beb760a654eced7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lyivxs-tweaks-1.21.4-fabric-1.0.0-dev-shadow.jar",
          "url": "lyivxs-tweaks-1.21.4-fabric-1.0.0-dev-shadow.jar",
          "size": 335635,
          "sha512": "c0f465b91e427b12566063a7e8105f0857b48e4bb17d198e459983ba5b73400275ed03e9796cbc396fd5ff51c512324921383a71d01d41c464b35560625b2ecd",
          "sha256": "03bb1e409b536c3ffb581140767ef713937dd879b26f9a07a1fb9a916d0fa1c9",
          "sha1": "49352def3fc06f3ebf1be3e1e3e505f7f6f02bc9",
          "md5": "10b4c86bded4813bbd20c11445ec436b"
        }
      ]
    }
  ]
}
